In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('kc_house_data.csv')

In [2]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [3]:
df.shape

(21613, 21)

In [4]:
from scipy import stats
df1 = df.drop(['id','date','lat','long','zipcode'], 1)
z = np.abs(stats.zscore(df1))
df1 = df1[(z < 3).all(axis=1)]
df1.fillna(df1.mean())
df1.shape

(18898, 16)

In [5]:
x = df1.iloc[:,1:]
y = df1.iloc[:,0]

In [6]:
print(x)
print (y)

       bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0
2             2       1.00          770     10000     1.0           0     0
3             4       3.00         1960      5000     1.0           0     0
4             3       2.00         1680      8080     1.0           0     0
6             3       2.25         1715      6819     2.0           0     0
7             3       1.50         1060      9711     1.0           0     0
8             3       1.00         1780      7470     1.0           0     0
9             3       2.50         1890      6560     2.0           0     0
11            2       1.00         1160      6000     1.0           0     0
12            3       1.00         1430     19901     1.5           0     0
13            3       1.75         1370      9680     1.0           0     0
14            5       2.00         1810      4850     1.5           0     0
16            3       2.00         1890     14040     2.0           0     0
17            4       1.00         1600      4300     1.5           0     0
18            2       1.00         1200      9850     1.0           0     0
19            3       1.00         1250      9774     1.0           0     0
20            4       1.75         1620      4980     1.0           0     0
22            5       2.50         2270      6300     2.0           0     0
23            2       1.50         1070      9643     1.0           0     0
24            3       2.25         2450      6500     2.0           0     0
25            3       2.00         1710      4697     1.5           0     0
26            3       1.75         2450      2691     2.0           0     0
27            3       1.00         1400      1581     1.5           0     0
28            3       1.75         1520      6380     1.0           0     0
29            4       2.50         2570      7173     2.0           0     0
30            3       2.50         2320      3980     2.0           0     0
31            2       1.50         1190      1265     3.0           0     0
32            4       1.75         2330      5000     1.5           0     0
33            3       1.00         1090      3000     1.5           0     0
34            4       2.75         2060      6659     1.0           0     0
...         ...        ...          ...       ...     ...         ...   ...
21581         3       3.00         2780      6000     2.0           0     0
21582         3       2.25         1500      1290     2.0           0     0
21583         2       1.00          710      1157     2.0           0     0
21584         3       2.50         1260       900     2.0           0     0
21585         3       2.50         1870      5000     2.0           0     0
21586         2       2.50         1430      1201     3.0           0     0
21587         3       2.50         1520      1488     3.0           0     0
21588         2       1.50         1210      1278     2.0           0     0
21589         3       2.50         2540      4760     2.0           0     0
21591         4       2.75         2770      3852     2.0           0     0
21592         3       2.25         1190      1200     3.0           0     0
21593         5       3.75         4170      8142     2.0           0     2
21594         4       2.75         2500      5995     2.0           0     0
21595         2       2.25         1530       981     3.0           0     0
21596         5       2.75         3600      9437     2.0           0     0
21597         4       3.25         3410     10125     2.0           0     0
21598         4       2.50         3118      7866     2.0           0     2
21599         4       3.00         3990      7838     2.0           0     0
21601         3       2.50         1425      1179     3.0           0     0
21602         3       1.75         1500     11968     1.0           0     0
21603         3       2.50         2270      5536     2.0           0     0
21604         3       2.00         1490      1126     3.0           0     0
21605         4       2.50         2520      6023     2.0           0     0
21606         4       3.50         3510      7200     2.0           0     0
21607         3       2.50         1310      1294     2.0           0     0
21608         3       2.50         1530      1131     3.0           0     0
21609         4       2.50         2310      5813     2.0           0     0
21610         2       0.75         1020      1350     2.0           0     0
21611         3       2.50         1600      2388     2.0           0     0
21612         2       0.75         1020      1076     2.0           0     0

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0              3      7        1180              0      1955             0
2              3      6         770              0      1933             0
3              5      7        1050            910      1965             0
4              3      8        1680              0      1987             0
6              3      7        1715              0      1995             0
7              3      7        1060              0      1963             0
8              3      7        1050            730      1960             0
9              3      7        1890              0      2003             0
11             4      7         860            300      1942             0
12             4      7        1430              0      1927             0
13             4      7        1370              0      1977             0
14             3      7        1810              0      1900             0
16             3      7        1890              0      1994             0
17             4      7        1600              0      1916             0
18             4      7        1200              0      1921             0
19             4      7        1250              0      1969             0
20             4      7         860            760      1947             0
22             3      8        2270              0      1995             0
23             3      7        1070              0      1985             0
24             4      8        2450              0      1985             0
25             5      6        1710              0      1941             0
26             3      8        1750            700      1915             0
27             5      8        1400              0      1909             0
28             3      7         790            730      1948             0
29             3      8        2570              0      2005             0
30             3      8        2320              0      2003             0
31             3      7        1190              0      2005             0
32             4      7        1510            820      1929             0
33             4      8        1090              0      1929             0
34             3      7        1280            780      1981             0
...          ...    ...         ...            ...       ...           ...
21581          3      9        2780              0      2013             0
21582          3      8        1220            280      2006             0
21583          4      7         710              0      1943             0
21584          3      7         940            320      2007             0
21585          3      7        1870              0      2009             0
21586          3      8        1430              0      2009             0
21587          3      8        1520              0      2006             0
21588          3      8        1020            190      2007             0
21589          3      8        2540              0      2010             0
21591          3      8        2770              0      2014             0
21592          3      8        1190              0      2008             0
21593          3     10        4170              0      2006             0
21594          3      8        2500              0      2008             0
21595          3      8        1480             50      2006             0
21596          3      9        3600              0      2014             0
21597          3     10        3410              0      2007             0
21598          3      9        3118              0      2014             0
21599          3      9        3990              0      2003             0
21601          3      8        1425              0      2008             0
21602          3      6        1500              0      2014             0
21603          3      8        2270              0      2003             0
21604          3      8        1490              0      2014             0
21605          3      9        2520              0      2014             0
21606          3      9        2600            910      2009             0
21607          3      8        1180            130      2008             0
21608          3      8        1530              0      2009             0
21609          3      8        2310              0      2014             0
21610          3      7        1020              0      2009             0
21611          3      8        1600              0      2004             0
21612          3      7        1020              0      2008             0

       sqft_living15  sqft_lot15
0               1340        5650
2               2720        8062
3               1360        5000
4               1800        7503
6               2238        6819
7               1650        9711
8               1780        8113
9               2390        7570
11              1330        6000
12              1780       12697
13              1370       10208
14              1360        4850
16              1890       14018
17              1610        4300
18              1060        5095
19              1280        8850
20              1400        4980
22              2240        7005
23              1220        8386
24              2200        6865
25              1030        4705
26              1760        3573
27              1860        3861
28              1520        6235
29              2630        6026
30              2580        3980
31              1390        1756
32              1460        5000
33              1570        5080
34              2020        8720
...              ...         ...
21581           2850        6000
21582           1460        1375
21583           1370        1173
21584           1310        1415
21585           2170        5399
21586           1430        1249
21587           1520        1497
21588           1210        1118
21589           2540        4571
21591           1810        5641
21592           1180        1224
21593           3030        7980
21594           2530        5988
21595           1530        1282
21596           3550        9421
21597           2290       10125
21598           2673        6500
21599           3370        6814
21601           1285        1253
21602           1320       11303
21603           2270        5731
21604           1400        1230
21605           2520        6023
21606           2050        6200
21607           1330        1265
21608           1530        1509
21609           1830        7200
21610           1020        2007
21611           1410        1287
21612           1020        1357

[18898 rows x 15 columns]
0         221900.0
2         180000.0
3         604000.0
4         510000.0
6         257500.0
7         291850.0
8         229500.0
9         323000.0
11        468000.0
12        310000.0
13        400000.0
14        530000.0
16        395000.0
17        485000.0
18        189000.0
19        230000.0
20        385000.0
22        285000.0
23        252700.0
24        329000.0
25        233000.0
26        937000.0
27        667000.0
28        438000.0
29        719000.0
30        580500.0
31        280000.0
32        687500.0
33        535000.0
34        322500.0
           ...
21581     625000.0
21582     490000.0
21583     399950.0
21584     380000.0
21585     270000.0
21586     505000.0
21587     385000.0
21588     414500.0
21589     347500.0
21591     572000.0
21592     475000.0
21593    1088000.0
21594     350000.0
21595     520000.0
21596     679950.0
21597    1575000.0
21598     541800.0
21599     810000.0
21601     467000.0
21602     224000.0
21603     507250.0
21604     429000.0
21605     610685.0
21606    1007500.0
21607     475000.0
21608     360000.0
21609     400000.0
21610     402101.0
21611     400000.0
21612     325000.0
Name: price, Length: 18898, dtype: float64

In [7]:
print (x)

       bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0             3       1.00         1180      5650     1.0           0     0
2             2       1.00          770     10000     1.0           0     0
3             4       3.00         1960      5000     1.0           0     0
4             3       2.00         1680      8080     1.0           0     0
6             3       2.25         1715      6819     2.0           0     0
7             3       1.50         1060      9711     1.0           0     0
8             3       1.00         1780      7470     1.0           0     0
9             3       2.50         1890      6560     2.0           0     0
11            2       1.00         1160      6000     1.0           0     0
12            3       1.00         1430     19901     1.5           0     0
13            3       1.75         1370      9680     1.0           0     0
14            5       2.00         1810      4850     1.5           0     0
16            3       2.00         1890     14040     2.0           0     0
17            4       1.00         1600      4300     1.5           0     0
18            2       1.00         1200      9850     1.0           0     0
19            3       1.00         1250      9774     1.0           0     0
20            4       1.75         1620      4980     1.0           0     0
22            5       2.50         2270      6300     2.0           0     0
23            2       1.50         1070      9643     1.0           0     0
24            3       2.25         2450      6500     2.0           0     0
25            3       2.00         1710      4697     1.5           0     0
26            3       1.75         2450      2691     2.0           0     0
27            3       1.00         1400      1581     1.5           0     0
28            3       1.75         1520      6380     1.0           0     0
29            4       2.50         2570      7173     2.0           0     0
30            3       2.50         2320      3980     2.0           0     0
31            2       1.50         1190      1265     3.0           0     0
32            4       1.75         2330      5000     1.5           0     0
33            3       1.00         1090      3000     1.5           0     0
34            4       2.75         2060      6659     1.0           0     0
...         ...        ...          ...       ...     ...         ...   ...
21581         3       3.00         2780      6000     2.0           0     0
21582         3       2.25         1500      1290     2.0           0     0
21583         2       1.00          710      1157     2.0           0     0
21584         3       2.50         1260       900     2.0           0     0
21585         3       2.50         1870      5000     2.0           0     0
21586         2       2.50         1430      1201     3.0           0     0
21587         3       2.50         1520      1488     3.0           0     0
21588         2       1.50         1210      1278     2.0           0     0
21589         3       2.50         2540      4760     2.0           0     0
21591         4       2.75         2770      3852     2.0           0     0
21592         3       2.25         1190      1200     3.0           0     0
21593         5       3.75         4170      8142     2.0           0     2
21594         4       2.75         2500      5995     2.0           0     0
21595         2       2.25         1530       981     3.0           0     0
21596         5       2.75         3600      9437     2.0           0     0
21597         4       3.25         3410     10125     2.0           0     0
21598         4       2.50         3118      7866     2.0           0     2
21599         4       3.00         3990      7838     2.0           0     0
21601         3       2.50         1425      1179     3.0           0     0
21602         3       1.75         1500     11968     1.0           0     0
21603         3       2.50         2270      5536     2.0           0     0
21604         3       2.00         1490      1126     3.0           0     0
21605         4       2.50         2520      6023     2.0           0     0
21606         4       3.50         3510      7200     2.0           0     0
21607         3       2.50         1310      1294     2.0           0     0
21608         3       2.50         1530      1131     3.0           0     0
21609         4       2.50         2310      5813     2.0           0     0
21610         2       0.75         1020      1350     2.0           0     0
21611         3       2.50         1600      2388     2.0           0     0
21612         2       0.75         1020      1076     2.0           0     0

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0              3      7        1180              0      1955             0
2              3      6         770              0      1933             0
3              5      7        1050            910      1965             0
4              3      8        1680              0      1987             0
6              3      7        1715              0      1995             0
7              3      7        1060              0      1963             0
8              3      7        1050            730      1960             0
9              3      7        1890              0      2003             0
11             4      7         860            300      1942             0
12             4      7        1430              0      1927             0
13             4      7        1370              0      1977             0
14             3      7        1810              0      1900             0
16             3      7        1890              0      1994             0
17             4      7        1600              0      1916             0
18             4      7        1200              0      1921             0
19             4      7        1250              0      1969             0
20             4      7         860            760      1947             0
22             3      8        2270              0      1995             0
23             3      7        1070              0      1985             0
24             4      8        2450              0      1985             0
25             5      6        1710              0      1941             0
26             3      8        1750            700      1915             0
27             5      8        1400              0      1909             0
28             3      7         790            730      1948             0
29             3      8        2570              0      2005             0
30             3      8        2320              0      2003             0
31             3      7        1190              0      2005             0
32             4      7        1510            820      1929             0
33             4      8        1090              0      1929             0
34             3      7        1280            780      1981             0
...          ...    ...         ...            ...       ...           ...
21581          3      9        2780              0      2013             0
21582          3      8        1220            280      2006             0
21583          4      7         710              0      1943             0
21584          3      7         940            320      2007             0
21585          3      7        1870              0      2009             0
21586          3      8        1430              0      2009             0
21587          3      8        1520              0      2006             0
21588          3      8        1020            190      2007             0
21589          3      8        2540              0      2010             0
21591          3      8        2770              0      2014             0
21592          3      8        1190              0      2008             0
21593          3     10        4170              0      2006             0
21594          3      8        2500              0      2008             0
21595          3      8        1480             50      2006             0
21596          3      9        3600              0      2014             0
21597          3     10        3410              0      2007             0
21598          3      9        3118              0      2014             0
21599          3      9        3990              0      2003             0
21601          3      8        1425              0      2008             0
21602          3      6        1500              0      2014             0
21603          3      8        2270              0      2003             0
21604          3      8        1490              0      2014             0
21605          3      9        2520              0      2014             0
21606          3      9        2600            910      2009             0
21607          3      8        1180            130      2008             0
21608          3      8        1530              0      2009             0
21609          3      8        2310              0      2014             0
21610          3      7        1020              0      2009             0
21611          3      8        1600              0      2004             0
21612          3      7        1020              0      2008             0

       sqft_living15  sqft_lot15
0               1340        5650
2               2720        8062
3               1360        5000
4               1800        7503
6               2238        6819
7               1650        9711
8               1780        8113
9               2390        7570
11              1330        6000
12              1780       12697
13              1370       10208
14              1360        4850
16              1890       14018
17              1610        4300
18              1060        5095
19              1280        8850
20              1400        4980
22              2240        7005
23              1220        8386
24              2200        6865
25              1030        4705
26              1760        3573
27              1860        3861
28              1520        6235
29              2630        6026
30              2580        3980
31              1390        1756
32              1460        5000
33              1570        5080
34              2020        8720
...              ...         ...
21581           2850        6000
21582           1460        1375
21583           1370        1173
21584           1310        1415
21585           2170        5399
21586           1430        1249
21587           1520        1497
21588           1210        1118
21589           2540        4571
21591           1810        5641
21592           1180        1224
21593           3030        7980
21594           2530        5988
21595           1530        1282
21596           3550        9421
21597           2290       10125
21598           2673        6500
21599           3370        6814
21601           1285        1253
21602           1320       11303
21603           2270        5731
21604           1400        1230
21605           2520        6023
21606           2050        6200
21607           1330        1265
21608           1530        1509
21609           1830        7200
21610           1020        2007
21611           1410        1287
21612           1020        1357

[18898 rows x 15 columns]

In [8]:
print (y)

0         221900.0
2         180000.0
3         604000.0
4         510000.0
6         257500.0
7         291850.0
8         229500.0
9         323000.0
11        468000.0
12        310000.0
13        400000.0
14        530000.0
16        395000.0
17        485000.0
18        189000.0
19        230000.0
20        385000.0
22        285000.0
23        252700.0
24        329000.0
25        233000.0
26        937000.0
27        667000.0
28        438000.0
29        719000.0
30        580500.0
31        280000.0
32        687500.0
33        535000.0
34        322500.0
           ...
21581     625000.0
21582     490000.0
21583     399950.0
21584     380000.0
21585     270000.0
21586     505000.0
21587     385000.0
21588     414500.0
21589     347500.0
21591     572000.0
21592     475000.0
21593    1088000.0
21594     350000.0
21595     520000.0
21596     679950.0
21597    1575000.0
21598     541800.0
21599     810000.0
21601     467000.0
21602     224000.0
21603     507250.0
21604     429000.0
21605     610685.0
21606    1007500.0
21607     475000.0
21608     360000.0
21609     400000.0
21610     402101.0
21611     400000.0
21612     325000.0
Name: price, Length: 18898, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_states=0)

ModuleNotFoundError: No module named 'sklearn'

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_states=0)

TypeError: Invalid parameters passed: {'random_states': 0}

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [12]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [13]:
y_pred=r.predict(x_test)

NameError: name 'r' is not defined

In [14]:
y_pred=reg.predict(x_test)

In [15]:
pred = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})

In [16]:
print (pred)

          Actual      Predicted
3530    445000.0  431953.335043
5599    350000.0  748668.278860
3509    535000.0  420638.181369
4644    560000.0  519748.875075
16818   607500.0  459490.939128
16610   270000.0  390300.805253
7105    330000.0  247693.982394
4043    580000.0  495957.056198
16034   782500.0  790929.559237
15174   612125.0  442669.665926
18838   540000.0  544450.204020
14198   199000.0  300954.784922
14629   277000.0  206447.431025
5752    565000.0  532559.857416
17806   539900.0  547204.739767
12842   305000.0  398604.048500
15839   500000.0  566336.677661
3473    275000.0  218509.455924
14635   532500.0  427068.719071
8690    404000.0  517522.868911
8971    392800.0  282441.953633
479     590000.0  694429.548087
878     229000.0  289596.537746
10501   390000.0  329585.724456
9321    290000.0  384422.246600
10442   239950.0  411345.954812
15821   525000.0  577078.869615
3242    491500.0  424982.882405
19206   585000.0  610180.099328
12096  1110000.0  706222.036592
...          ...            ...
2756    370000.0  339112.500322
9433    272000.0  429329.167265
1801    615000.0  662358.437157
603     460000.0  288919.581101
1535    900000.0  843408.973239
12722   325000.0  158316.520227
10359   216000.0  404520.364502
20964   533380.0  531698.916611
4256    261500.0  558519.333790
16549   338000.0  356286.106383
18374   290000.0  327807.597058
611     650000.0  671804.053866
13664   655000.0  674012.520291
12708   475200.0  446999.980177
21373   325000.0  432829.442137
16421   424950.0  546681.382265
626     559950.0  564790.128430
16414   322968.0  413787.100224
993     253000.0  282012.548795
13162   310000.0  354558.583701
5695    625000.0  535163.940813
17051   190000.0  323284.311421
19296   585000.0  489514.507597
11084   814950.0  663621.990832
13848   300000.0  439164.977074
11969   249000.0  258687.264142
18996   449999.0  639854.380920
4402    515000.0  451506.327286
15861   286000.0  280744.173731
6161    525000.0  512901.494493

[5670 rows x 2 columns]

In [17]:
from sklearn import metrics

In [18]:
print('Mean Absolute Error: ', metrics.mean_absolute_error(y_test, y_pred))

print('Mean Squared Error: ', metrics.mean_squared_error(y_test, y_pred))

print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error:  110558.10140740039
Mean Squared Error:  22473585318.50556
Root Mean Squared Error:  149911.92520445317

In [19]:
print (reg.score(x_test,y_test))

0.5661880394527972